version: "3.8"

networks:
  front-connection:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always

    #클라이언트가 8000 PORT 로 들어온다. 
    ports: 
      - "8000:8000"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
  
    networks:
      - front-connection
    environment:
      - TZ=Asia/Seoul

  express:
    container_name: express
    build:
      context: .
      dockerfile: dockerfile
    restart: always

    networks:
      - front-connection
 